
import {
  ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ArrowUpTrayIcon as ArrowUpTrayIconMini,
  XMarkIcon as XMarkIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  CheckIcon as CheckIconMini,
  PlusIcon as Plus,
  Bars3CenterLeftIcon as MenuBar,
  Bars3CenterLeftIcon as BarsIcon,
} from "@heroicons/react/20/solid";

import {
  InformationCircleIcon,
  PlusIcon,
  ChevronDownIcon,
  XMarkIcon,
  TrashIcon,
  PencilIcon,
  HomeIcon as Homeicon,
  QuestionMarkCircleIcon as Helpicon,
  UserPlusIcon as Contactsicon,
  BanknotesIcon as Withdrawicon,
  DocumentIcon as Invoicesicon,
  Cog8ToothIcon as Settings,
  ArrowRightOnRectangleIcon as LogOuticon,
  ArrowDownTrayIcon as Download,
  MagnifyingGlassIcon as MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIcon,
  ArrowsUpDownIcon as ArrowsUpDownIcon,
  UserCircleIcon as User,
  PaperAirplaneIcon as Send,
  ArrowLeftIcon as ArrowLeftIcon,
  HomeIcon as HomeIcon,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleIcon,
  Cog8ToothIcon as Cog8ToothIcon,
  QuestionMarkCircleIcon,
  ArrowDownTrayIcon as ArrowDownTrayIcon,
  Bars3Icon as Bars3Icon,
  MagnifyingGlassIcon as SearchIcon,

} from "@heroicons/react/24/outline";

export {
  ErrorIconMini,
  CheckCircleIconMini,
  EyeIconMini,
  EyeSlashIconMini,
  ChevronLeftIconMini,
  ArrowUpTrayIconMini,
  XMarkIconMini,
  InformationCircleIconMini,
  InformationCircleIcon,
  CheckIconMini,
  PlusIcon,
  ChevronDownIcon,
  XMarkIcon,
  TrashIcon,
  PencilIcon,
  Homeicon,
  Helpicon,
  Contactsicon,
  Withdrawicon,
  Invoicesicon,
  Settings,
  LogOuticon,
  Download,
  User,
  Send,
  Plus,
  MenuBar,
  ArrowLeftIcon,
  HomeIcon,
  ArrowRightOnRectangleIcon,
  Cog8ToothIcon,
  QuestionMarkCircleIcon,
  ArrowDownTrayIcon,
  Bars3Icon,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  ArrowsUpDownIcon,
  SearchIcon,
  BarsIcon
};
